# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bidi_api.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62idi_api.proto\x12\x0b\x61iserver.v1\"#\n\rBidiRequestId\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"|\n\x11\x42idiAppendRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12.\n\nrequest_id\x18\x02 \x01(\x0b\x32\x1a.aiserver.v1.BidiRequestId\x12\x14\n\x0c\x61ppend_seqno\x18\x03 \x01(\x03\x12\x13\n\x0b\x64\x61ta_binary\x18\x04 \x01(\x0c\"\x14\n\x12\x42idiAppendResponse\"o\n\x0f\x42idiPollRequest\x12.\n\nrequest_id\x18\x01 \x01(\x0b\x32\x1a.aiserver.v1.BidiRequestId\x12\x1a\n\rstart_request\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x10\n\x0e_start_request\"I\n\x10\x42idiPollResponse\x12\r\n\x05seqno\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x10\n\x03\x65of\x18\x03 \x01(\x08H\x00\x88\x01\x01\x42\x06\n\x04_eofb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidi_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIDIREQUESTID']._serialized_start=31
  _globals['_BIDIREQUESTID']._serialized_end=66
  _globals['_BIDIAPPENDREQUEST']._serialized_start=68
  _globals['_BIDIAPPENDREQUEST']._serialized_end=192
  _globals['_BIDIAPPENDRESPONSE']._serialized_start=194
  _globals['_BIDIAPPENDRESPONSE']._serialized_end=214
  _globals['_BIDIPOLLREQUEST']._serialized_start=216
  _globals['_BIDIPOLLREQUEST']._serialized_end=327
  _globals['_BIDIPOLLRESPONSE']._serialized_start=329
  _globals['_BIDIPOLLRESPONSE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
